---
title: "Bist5361_HW9"
author: "Ian Weykamp"
date: "11/5/2020"
output: html_document
---

(7.5.1)
a.
````{r}
set.seed(123)

f <- function(x) 1/(5* sqrt(2 * pi)) * x^2 * exp(-(x - 2)^2 / 2)

nrep <- 1000
n <- 10000

#1000
i.n <- replicate(nrep, {x <- rnorm(n, 0, 1); mean(f(x) / dnorm(x, 0, 1))})
mean(i.n)
sd(i.n)
#10000
i.n <- replicate(10000, {x <- rnorm(n, 0, 1); mean(f(x) / dnorm(x, 0, 1))})
mean(i.n)
sd(i.n)
#50000
i.n <- replicate(50000, {x <- rnorm(n, 0, 1); mean(f(x) / dnorm(x, 0, 1))})
mean(i.n)
sd(i.n)


#b.

i.n <- replicate(nrep, {x <- rnorm(n, 2, 1); mean(f(x) / dnorm(x, 2, 1))})
mean(i.n)
sd(i.n)
i.n <- replicate(10000, {x <- rnorm(n, 2, 1); mean(f(x) / dnorm(x, 2, 1))})
mean(i.n)
sd(i.n)
i.n <- replicate(50000, {x <- rnorm(n, 2, 1); mean(f(x) / dnorm(x, 2, 1))})
mean(i.n)
sd(i.n)
````
When using g(x)~N(2,1) we see a much smaller variance and a mean closer to 1.
We use this g(x) because the function f(x) is much more simliar to a normal
distribution with mean 2 than it is to a normal distribution with mean 0.

(7.5.2)
````{r}
set.seed(100)
#a - path
t <- 0:100 
sig2 <- 0.25
x <- rnorm(n = length(t) - 1, sd = sqrt(sig2))
x <- c(0, cumsum(x))
plot(t, x, type = "l", ylim = c(-2, 3))

#Prof's code for BM - minor adjustments made
rBM <- function(n, tgrid, sigma) {
    tt <- c(0, tgrid)
    dt <- diff(tt)
    nt <- length(tgrid)
    dw <- matrix(rnorm(n * nt, sd = sigma * sqrt(dt)), n, nt, byrow = TRUE)
    t(apply(dw, 1, cumsum))
}
callValLognorm <- function(S0, K, mu, sigma) {
    d <- (log(S0 / K) + mu + sigma^2) / sigma
    S0 * exp(mu + 0.5 * sigma^2) * pnorm(d) - K * pnorm(d - sigma)
}
optValueAppr <- function(n, r, sigma, S0, K, tgrid) {
    wt <- rBM(n, tgrid, sigma)
    ## payoff of call option on arithmetic average
    nt <- length(tgrid)
    TT <- tgrid[nt]
    St <- S0 * exp((r - sigma^2 / 2) * matrix(tgrid, n, nt, byrow = TRUE) + wt)
    pAri <- pmax(rowMeans(St) - K, 0)
    vAri <- mean(pAri) 
    ## underlying asset price
    ST <- St[, nt]
    vAs <- vAri - cov(ST, pAri) / var(ST) * (mean(ST) - exp(r * TT) * S0)
    ## value of standard option
    pStd <- pmax(ST - K, 0)
    pStdTrue <- callValLognorm(S0, K, (r - 0.5 * sigma^2) * TT,
                               sigma * sqrt(TT))
    vStd <-  vAri - cov(pStd, pAri) / var(pStd) * (mean(pStd) - pStdTrue)
    ## payoff of call option on geometric average
    pGeo <- pmax(exp(rowMeans(log(St))) - K, 0)
    tbar <- mean(tgrid)
    sBar2 <- sigma^2 / nt^2 / tbar * sum( (2 * seq(nt) - 1) * rev(tgrid) )
    pGeoTrue <- callValLognorm(S0, K, (r - 0.5 * sigma^2) * tbar,
                               sqrt(sBar2 * tbar))
    vGeo <- vAri - cov(pGeo, pAri) / var(pGeo) * (mean(pGeo) - pGeoTrue)
    ## sim <- data.frame(pAri, ST, pStd, pGeo)
    ## result
    c(vAri, vAs, vStd, vGeo) * exp(-r * TT)
    #p_a, s(t), p_e, p_g
}
cat("Changes in K \n")

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.1; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.2; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.3; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.4; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

###
cat("Changes in sigma \n")
###

r <- 0.05; sigma <- 0.2; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.3; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.4; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

###
cat("Changes in T \n")
###

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 0.4, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 0.7, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1.3, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

r <- 0.05; sigma <- 0.5; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1.6, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

####
cat("E\n")
####

r <- 0.05; sigma <- 0.4; S0 <-  50; K <- 1.5; n <- 12
tgrid <-  seq(0, 1, length = 10)[-1]
sim <- replicate(5000, optValueAppr(n, r, sigma, S0, K, tgrid))
apply(sim, 1, mean)
apply(sim, 1, sd)

cov(sim[1,],sim[2,]) #cov Pa, ST
cov(sim[1,],sim[3,]) #cov Pa, Pe
cov(sim[1,],sim[4,]) #cov Pa, Pg

````
As sigma and T increase, the covariance terms all increase.  There is no direct partern for the small increments in K.

$E(P_g)=47.43615, E(P_a)=47.35332$.
$SD(P_G)=0.177909, SD(P_A)=3.60173$.
